### ISSUE TITLE
Regression when creating an mzi. Maybe something wrong with reference.mirror() ?

### ISSUE THREAD

**Issue by flaport** [gdsfactory/gdsfactory#2881]
The following code works for both gdsfactory7 and 8:

```python
@gf.cell
def simple_mzi():
    c = gf.Component()

    # components
    mmi_in = gf.components.mmi1x2()
    mmi_out = gf.components.mmi2x2()
    bend = gf.components.bend_euler()
    half_delay_straight = gf.components.straight(length=10.0)

    # references
    mmi_in_ref = c << mmi_in
    mmi_out_ref = c << mmi_out
    straight_top1_ref = c << half_delay_straight
    straight_top2_ref = c << half_delay_straight
    bend_top1_ref = c << bend
    bend_top2_ref = (c << bend).mirror()
    bend_top3_ref = (c << bend).mirror()
    bend_top4_ref = c << bend
    bend_btm1_ref = (c << bend).mirror()
    bend_btm2_ref = c << bend
    bend_btm3_ref = c << bend
    bend_btm4_ref = (c << bend).mirror()

    # connections
    bend_top1_ref.connect("o1", mmi_in_ref.ports["o2"])
    straight_top2_ref.connect("o1", bend_top1_ref.ports["o2"])
    bend_top2_ref.connect("o1", straight_top1_ref.ports["o2"])
    bend_top3_ref.connect("o1", bend_top2_ref.ports["o2"])
    straight_top2_ref.connect("o1", bend_top3_ref.ports["o2"])
    bend_top4_ref.connect("o1", straight_top2_ref.ports["o2"])

    bend_btm1_ref.connect("o1", mmi_in_ref.ports["o3"])
    bend_btm2_ref.connect("o1", bend_btm1_ref.ports["o2"])
    bend_btm3_ref.connect("o1", bend_btm2_ref.ports["o2"])
    bend_btm4_ref.connect("o1", bend_btm3_ref.ports["o2"])

    mmi_out_ref.connect("o1", bend_btm4_ref.ports["o2"])

    # ports
    c.add_port(
        "o1",
        port=mmi_in_ref.ports["o1"],
    )
    c.add_port("o2", port=mmi_out_ref.ports["o3"])
    c.add_port("o3", port=mmi_out_ref.ports["o4"])
    return c
```

But both give pretty different results:

gdsfactory7 (as expected):
![image](https://github.com/gdsfactory/gdsfactory/assets/15832886/0734f2c2-a6a1-4951-b578-22a7f6c5ed9c)

gdsfactory8 (unfortunately):
![image](https://github.com/gdsfactory/gdsfactory/assets/15832886/af2f3174-3a7b-4087-ad65-72ccb417d953)

Not 100% sure, but the .mirror method of the references seem inconsistent.

**Comment by sebastian-goeldi** [comment]
You have a small typo:

```python
# connections
bend_top1_ref.connect("o1", mmi_in_ref.ports["o2"])
straight_top1_ref.connect("o1", bend_top1_ref.ports["o2"]) # was straight_top2 but should be 1
```

and yes, there is a problem in kfactory. The initial port was taking over the mirror flag

**Comment by flaport** [comment]
Thanks for the quick fix! Just checked (and fixed the typo locally) and it works!

**Comment by flaport** [comment]
@joamatab can you make a GDS factory patch release depending on the fixed kfactory?

**Comment by sebastian-goeldi** [comment]
I didn't release yet. I want to fix some routing issues first.

**Comment by flaport** [comment]
Yeah, I think that there are also still some issues in gdsfactory that need to be fixed.

For example:

![image](https://github.com/gdsfactory/gdsfactory/assets/15832886/6ca89bd3-4bb6-4caa-9beb-9d9ca362bad5)

@joamatab 

opening this issue again for now.

**Comment by sebastian-goeldi** [comment]
@flaport I think this is fixed now? I am not 100% sure, but yesterday @joamatab deployed several fixes

**Comment by joamatab** [comment]
```python
import gdsfactory as gf 

@gf.cell
def simple_mzi():
    c = gf.Component()

    # components
    mmi_in = gf.components.mmi1x2()
    mmi_out = gf.components.mmi2x2()
    bend = gf.components.bend_euler()
    half_delay_straight = gf.components.straight(length=10.0)

    # references
    mmi_in_ref = c << mmi_in
    mmi_out_ref = c << mmi_out
    straight_top1_ref = c << half_delay_straight
    straight_top2_ref = c << half_delay_straight
    bend_top1_ref = c << bend
    bend_top2_ref = (c << bend).mirror()
    bend_top3_ref = (c << bend).mirror()
    bend_top4_ref = c << bend
    bend_btm1_ref = (c << bend).mirror()
    bend_btm2_ref = c << bend
    bend_btm3_ref = c << bend
    bend_btm4_ref = (c << bend).mirror()

    # connections
    bend_top1_ref.connect("o1", mmi_in_ref.ports["o2"])
    straight_top1_ref.connect("o1", bend_top1_ref.ports["o2"]) # was straight_top2 but should be 1

    straight_top2_ref.connect("o1", bend_top1_ref.ports["o2"])
    bend_top2_ref.connect("o1", straight_top1_ref.ports["o2"])
    bend_top3_ref.connect("o1", bend_top2_ref.ports["o2"])
    straight_top2_ref.connect("o1", bend_top3_ref.ports["o2"])
    bend_top4_ref.connect("o1", straight_top2_ref.ports["o2"])

    bend_btm1_ref.connect("o1", mmi_in_ref.ports["o3"])
    bend_btm2_ref.connect("o1", bend_btm1_ref.ports["o2"])
    bend_btm3_ref.connect("o1", bend_btm2_ref.ports["o2"])
    bend_btm4_ref.connect("o1", bend_btm3_ref.ports["o2"])

    mmi_out_ref.connect("o1", bend_btm4_ref.ports["o2"])

    # ports
    c.add_port(
        "o1",
        port=mmi_in_ref.ports["o1"],
    )
    c.add_port("o2", port=mmi_out_ref.ports["o3"])
    c.add_port("o3", port=mmi_out_ref.ports["o4"])
    return c


c = simple_mzi()
c.show()

```

this works great for me

**Comment by flaport** [comment]
Hi @joamatab @sebastian-goeldi , thanks! I think we're getting really close!

Unfortunately, it's not yet fixed in `gf.read.from_yaml`. More specifically, the mirror argument is ignored in placements when a connection is made (see minimal example)... i.e. the resulting GDS looks the same when the mirror placement is there or not.


**minimal example:**

```python
import gdsfactory as gf
yaml = """
pdk: cspdk.si220
instances:
  c1:
    component: coupler_sc
    settings: {}
  b1:
    component: bend_sc
    settings: {}
  b2:
    component: bend_sc
    settings: {}
connections:
  c1,o3: b1,o1
  b2,o1: b1,o2
ports: {}
placements:
  b2:
    mirror: true
"""
c = gf.read.from_yaml(yaml)
c.show()
```

This is how the GDS looks:

![image](https://github.com/gdsfactory/gdsfactory/assets/15832886/9c18b0e3-837b-4e45-9230-9260ffedfe75)

In the case of `mirror: true` for bend `b2` the bend `b2` should point the other way.

**Comment by joamatab** [comment]
this is how it looks with the fix



![Image](https://github.com/gdsfactory/gdsfactory/assets/4514346/18258bca-758b-4480-8291-097c471e6b24)

**Comment by flaport** [comment]
@joamatab , still not correct. It should look like this:

![image](https://github.com/gdsfactory/gdsfactory/assets/15832886/7a4de444-7ece-4776-ab25-799c7e20f287)

**Comment by flaport** [comment]
I suggest to use my fix in #2936 in stead.

**Comment by joamatab** [comment]
The original mirror/connect regression was fixed in kfactory and the corrected MZI example now works on current gdsfactory. The later YAML mirror behavior was handled separately by the YAML placement fixes.
