### ISSUE TITLE
RuntimeError: Internal error: src/db/db/dbLayout.cc:1861 topological_sort () was not true in Cell.called_cells

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#3613]
```python
    import gdsfactory as gf

    c = gf.c.bend_euler_all_angle(angle=45)
    c.write_gds("bend_euler_all_angle.gds")
    c.show()
```

@MatthewMckee4 
@sebastian-goeldi

**Comment by MatthewMckee4** [comment]
related to https://github.com/gdsfactory/kfactory/issues/550

**Comment by MatthewMckee4** [comment]
i think it just fails in general (not sure though)

**Comment by sebastian-goeldi** [comment]
Should be fixed now that klayout 0.29.11 released

**Comment by joamatab** [comment]
it's not fixed, i upgraded to latest klayout and the issue still persists

**Comment by MatthewMckee4** [comment]
yeah, still there

**Comment by sebastian-goeldi** [comment]
Sorry, yeah, there's a bug in kfactory. It's trying to insert the cell into itself

**Comment by sebastian-goeldi** [comment]
This should be fixed in >=0.23.2, yes?

**Comment by joamatab** [comment]
yes, it was, we still has some issues with some custom clear_cache functions

i'll try to create a new issue for that

**Comment by sebastian-goeldi** [comment]
oh, we probably should use klayout >=0.29.11, I don't think kfactory pinned it. But soon we will use `Cell.locked` to actually lock creation of shapes and modifications, so requiring 0.29.11 makes sense

**Comment by joamatab** [comment]
even with klayout 0.29.11 i  still see that issue

**Comment by sebastian-goeldi** [comment]
cannot reproduce

- recreated env
- installed latest dependencies
- ran MWE successfully
- check kfactory for relevant code which is there
